export const TOTP_USER_SECRET = "RW5SJG5SRCHL3YEBPUOOIB6W5VDOF4MA";

export const WEBAUTHN_PRIVATE_KEY =
	"MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgfMg3KfIHfTSLYIhDFTnXi8lB8T52UdBOjIhdD1m9CeChRANCAAQDT8BRVawt/UpbT6h0JuMwWCMNGZ6jVxQIU02/mxEWnom5auTiF5rgWsXPyfsvlkJ77ROER8q2+blW/9EfALNs";

export const WEBAUTHN_PRIVATE_KEY_BYTES = Uint8Array.from(
	atob(WEBAUTHN_PRIVATE_KEY),
	(c) => c.charCodeAt(0),
);

// cooldowns

export const PASSWORD_RESET_TOKEN_COOLDOWN = 20_000 + 2_000; // add buffer

export const EMAIL_VERIFICATION_TOKEN_COOLDOWN = 20_000 + 2_000; // add buffer
