name: medical_jobs
root: ./

windows:
  - server:
      - cd server
      - uv run scripts/run_server.py
  -  persist_server:
      - cd server
      - uv run scripts/run_persist_server.py

  - seeker_portal:
      - pnpm --filter seeker-portal dev

  - recruiter_portal_core:
      - pnpm --filter recruiter-portal-core dev

  - recruiter_dashboard:
      - pnpm --filter recruiter-dashboard dev

  - accounts:
      - pnpm --filter accounts dev

  - relay-compiler:
      - relay-compiler --watch

  - docker:
      - docker compose up
