services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80 # http
      - 443 # https
    volumes:
      - caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs/localtest.me.pem:/etc/caddy/certs/localtest.me.pem:ro
      - ./certs/localtest.me-key.pem:/etc/caddy/certs/localtest.me-key.pem:ro
    environment:
      - SEEKER_PORTAL_HOST=host.docker.internal
      - ACCOUNTS_HOST=host.docker.internal
      - SERVER_HOST=host.docker.internal
      - RECRUITER_PORTAL_CORE_HOST=host.docker.internal
      - RECRUITER_DASHBOARD_HOST=host.docker.internal

  mongodb:
    image: mongodb/mongodb-atlas-local:8.0.133
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
      - RUNNER_LOG_FILE=/dev/stderr

  redis:
    image: docker.io/bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes # Or set a password with REDIS_PASSWORD
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis/data

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - "1080:1080"
      - "1025:1025"

  smscatcher:
    build:
      context: ./sms-catcher
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    environment:
      - SERVER_DEBUG=False
      - SERVER_ENVIRONMENT=production
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=4444
      - SERVER_LOG_LEVEL=INFO

  minio:
    build:
      context: ./minio
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/bitnami/minio/data'
    environment:
      - MINIO_ROOT_USER=minio-access-key
      - MINIO_ROOT_PASSWORD=minio-secret-key
      - MINIO_DEFAULT_BUCKETS=medicaljobs:readonly
      - MINIO_SERVER_URL=http://localhost:9000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  nominatim:
    image: mediagis/nominatim:5.1
    ports:
        - "8080:8080"
    environment:
        # see https://github.com/mediagis/nominatim-docker/tree/master/5.1#configuration for more options
        PBF_URL: https://download.geofabrik.de/europe/monaco-latest.osm.pbf
        REPLICATION_URL: https://download.geofabrik.de/europe/monaco-updates/
        NOMINATIM_PASSWORD: pass
    volumes:
        - nominatim_data:/var/lib/postgresql/16/main
    shm_size: 1gb


volumes:
  mongodb_data:
    driver: local
  minio_data:
    driver: local
  nominatim_data:
    driver: local
  caddy_data:
    driver: local
  redis_data:
    driver: local
