name: Build and Deploy Accounts UI

on:
  workflow_call:
    inputs:
      run-deploy:
        required: true
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name == 'production' && 'production' || 'staging' }}  # Ensures only one run of this workflow at a time
  cancel-in-progress: false      # Waits instead of cancelling previous runs


env:  # repo-level and non-env-specific secrets/vars
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYMENT_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYMENT_AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  build-and-push:
    if: ${{ inputs.run-deploy }}
    environment: ${{ github.ref_name == 'production' && 'production' || 'staging' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - uses: actions/cache@v4
        with:
          # Cache the .next/cache folder for the apps/accounts app
          path: |
            apps/accounts/.next/cache
          # Generate a new cache whenever the lockfile or source files change
          key: ${{ runner.os }}-nextjs-accounts-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('apps/accounts/**/*.[jt]s', 'apps/accounts/**/*.[jt]sx', 'apps/accounts/**/*.{css,md,mdx}') }}
          # If source files changed but pnpm-lock.yaml didn’t, use the previous cache
          restore-keys: |
            ${{ runner.os }}-nextjs-accounts-${{ hashFiles('pnpm-lock.yaml') }}-

      - name: Install dependencies
        run: pnpm install --filter accounts --frozen-lockfile --shamefully-hoist

      - name: Validate Relay Compiler Artifacts
        run: pnpm --filter accounts run relay --validate

      - name: SST Deploy
        working-directory: ./apps/accounts
        run: npx sst deploy --stage ${{ github.ref_name == 'production' && 'production' || 'staging' }} --print-logs
        env:
            SST_VPC_PRIVATE_SUBNETS: ${{ vars.SST_VPC_PRIVATE_SUBNETS }}
            SST_VPC_SECURITY_GROUPS: ${{ vars.SST_VPC_SECURITY_GROUPS }}
            SST_ACCOUNTS_DOMAIN: ${{vars.SST_ACCOUNTS_DOMAIN }}
            SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
            NEXT_PUBLIC_API_URL: ${{ vars.SST_API_URL }}
            NEXT_PUBLIC_INTERNAL_API_URL: ${{ vars.SST_API_URL }}
            NEXT_PUBLIC_URL: ${{ vars.SST_ACCOUNTS_BASE_URL }}
            NEXT_PUBLIC_CAPTCHA_SITE_KEY: ${{ vars.SST_CAPTCHA_SITE_KEY }}
            NEXT_PUBLIC_RECRUITER_PORTAL_BASE_URL: ${{ vars.SST_RECRUITER_PORTAL_BASE_URL }}
            NEXT_PUBLIC_SEEKER_PORTAL_BASE_URL: ${{ vars.SST_SEEKER_PORTAL_BASE_URL}}
            NEXT_PUBLIC_SESSION_COOKIE_KEY: user_session
            NEXT_PUBLIC_ENVIRONMENT: production
            NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.ACCOUNTS_SENTRY_DSN }}
            NEXT_PUBLIC_SENTRY_ORGANIZATION: ${{ vars.SENTRY_ORGANIZATION }}
            NEXT_PUBLIC_SENTRY_PROJECT: ${{vars.ACCOUNTS_SENTRY_PROJECT}}
            NEXT_PUBLIC_ROOT_DOMAIN: ${{ vars.PUBLIC_ROOT_DOMAIN }}
            AWS_SECRET_ID: ${{ secrets.SST_ACCOUNTS_SECRET_ID }}
            SKIP_ENV_VALIDATION: true
            NODE_ENV: production
            BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
            BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
            NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.POSTHOG_API_KEY }}
            NEXT_PUBLIC_POSTHOG_HOST: ${{ vars.POSTHOG_API_HOST }}
