name: Deploy and Run E2E

on:
  push:
    branches: [staging, production]

jobs:
  changes:
      runs-on: ubuntu-latest
      outputs:
        backend: ${{ steps.filter.outputs.backend }}
        worker: ${{ steps.filter.outputs.worker }}
        accounts_ui: ${{ steps.filter.outputs.accounts_ui }}
        recruiter_dashboard_ui: ${{ steps.filter.outputs.recruiter_dashboard_ui }}
        recruiter_portal_ui: ${{ steps.filter.outputs.recruiter_portal_ui }}
        seeker_portal_ui: ${{ steps.filter.outputs.seeker_portal_ui }}
        infra: ${{ steps.filter.outputs.infra }}
        shared_infra: ${{ steps.filter.outputs.shared_infra }}
        e2e_tests: ${{ steps.filter.outputs.e2e_tests }}
      steps:
      - uses: actions/checkout@v4
        with:
          # This may save additional git fetch roundtrip if
          # merge-base is found within latest 20 commits
          fetch-depth: 20
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          ref: staging
          filters: |
            backend:
              - 'server/**'
              - '.github/workflows/deploy-backend.yml'
            worker:
              - 'server/**'
              - '.github/workflows/deploy-worker.yml'
            accounts_ui:
              - 'apps/accounts/**'
              - '.github/workflows/deploy-accounts-ui.yml'
            recruiter_dashboard_ui:
              - 'apps/recruiter-dashboard/**'
              - '.github/workflows/deploy-recruiter-dashboard-ui.yml'
            recruiter_portal_ui:
              - 'apps/recruiter-portal-core/**'
              - '.github/workflows/deploy-recruiter-portal-core-ui.yml'
            seeker_portal_ui:
              - 'apps/seeker-portal/**'
              - '.github/workflows/deploy-seeker-portal-ui.yml'
            e2e_tests:
              - '.github/workflows/e2e-tests.yml'
            infra:
              - 'infrastructure/production/**'
              - 'infrastructure/staging/**'
              - 'infrastructure/modules/**'
              - '.github/workflows/apply-infrastructure.yml'
            shared_infra:
              - 'infrastructure/shared/**'
              - '.github/workflows/apply-shared-infrastructure.yml'
      - run: |
          echo "Backend: ${{ steps.filter.outputs.backend == 'true' }}"
          echo "Worker: ${{ steps.filter.outputs.worker == 'true' }}"
          echo "Accounts UI: ${{ steps.filter.outputs.accounts_ui == 'true' }}"
          echo "Recruiter Dashboard UI: ${{ steps.filter.outputs.recruiter_dashboard_ui == 'true' }}"
          echo "Recruiter Portal UI: ${{ steps.filter.outputs.recruiter_portal_ui == 'true' }}"
          echo "Seeker Portal UI: ${{ steps.filter.outputs.seeker_portal_ui == 'true' }}"
          echo "E2E Tests: ${{ steps.filter.outputs.e2e_tests == 'true' }}"
          echo "Infra: ${{ steps.filter.outputs.infra == 'true' }}"
          echo "Shared Infra: ${{ steps.filter.outputs.shared_infra == 'true' }}"
  deploy-backend:
    if: ${{ needs.changes.outputs.backend == 'true' && (needs.deploy-shared-infra.result == 'success' || needs.deploy-shared-infra.result == 'skipped') && (needs.deploy-infra.result == 'success' || needs.deploy-infra.result == 'skipped') }}
    uses: ./.github/workflows/deploy-backend.yml
    secrets: inherit
    needs:
        - changes
        - deploy-shared-infra
        - deploy-infra

  deploy-worker:
    if: ${{ needs.changes.outputs.worker == 'true' && (needs.deploy-shared-infra.result == 'success' || needs.deploy-shared-infra.result == 'skipped') && (needs.deploy-infra.result == 'success' || needs.deploy-infra.result == 'skipped') }}
    uses: ./.github/workflows/deploy-worker.yml
    secrets: inherit
    needs:
        - changes
        - deploy-shared-infra
        - deploy-infra

  deploy-accounts-ui:
    if: ${{ needs.changes.outputs.accounts_ui == 'true' && (needs.deploy-backend.result == 'success' || needs.deploy-backend.result == 'skipped') && (needs.deploy-shared-infra.result == 'success' || needs.deploy-shared-infra.result == 'skipped') && (needs.deploy-infra.result == 'success' || needs.deploy-infra.result == 'skipped') }}
    uses: ./.github/workflows/deploy-accounts-ui.yml
    secrets: inherit
    needs:
      - changes
      - deploy-backend
      - deploy-shared-infra
      - deploy-infra

  deploy-recruiter-dashboard-ui:
    if: ${{ needs.changes.outputs.recruiter_dashboard_ui == 'true' && (needs.deploy-backend.result == 'success' || needs.deploy-backend.result == 'skipped') && (needs.deploy-shared-infra.result == 'success' || needs.deploy-shared-infra.result == 'skipped') && (needs.deploy-infra.result == 'success' || needs.deploy-infra.result == 'skipped') }}
    uses: ./.github/workflows/deploy-recruiter-dashboard-ui.yml
    secrets: inherit
    needs:
      - changes
      - deploy-backend
      - deploy-shared-infra
      - deploy-infra

  deploy-recruiter-portal-ui:
    if: ${{ needs.changes.outputs.recruiter_portal_ui == 'true' && (needs.deploy-backend.result == 'success' || needs.deploy-backend.result == 'skipped') && (needs.deploy-shared-infra.result == 'success' || needs.deploy-shared-infra.result == 'skipped') && (needs.deploy-infra.result == 'success' || needs.deploy-infra.result == 'skipped') }}
    uses: ./.github/workflows/deploy-recruiter-portal-core-ui.yml
    secrets: inherit
    needs:
      - changes
      - deploy-backend
      - deploy-shared-infra
      - deploy-infra

  deploy-seeker-portal-ui:
    if: ${{ needs.changes.outputs.seeker_portal_ui == 'true' && (needs.deploy-backend.result == 'success' || needs.deploy-backend.result == 'skipped') && (needs.deploy-shared-infra.result == 'success' || needs.deploy-shared-infra.result == 'skipped') && (needs.deploy-infra.result == 'success' || needs.deploy-infra.result == 'skipped') }}
    uses: ./.github/workflows/deploy-seeker-portal-ui.yml
    secrets: inherit
    needs:
      - changes
      - deploy-backend
      - deploy-shared-infra
      - deploy-infra

  deploy-shared-infra:
    if: ${{ needs.changes.outputs.shared_infra == 'true' }}
    uses: ./.github/workflows/apply-shared-infrastructure.yml
    secrets: inherit
    needs: changes
  deploy-infra:
    if: ${{ needs.changes.outputs.infra == 'true' && (needs.deploy-shared-infra.result == 'success' || needs.deploy-shared-infra.result == 'skipped') }}
    uses: ./.github/workflows/apply-infrastructure.yml
    secrets: inherit
    needs:
      - changes
      - deploy-shared-infra

  e2e-tests:
    if: ${{ github.ref == 'refs/heads/staging' && (needs.changes.outputs.backend == 'true' || needs.changes.outputs.worker == 'true' || needs.changes.outputs.accounts_ui == 'true' || needs.changes.outputs.recruiter_dashboard_ui == 'true' || needs.changes.outputs.recruiter_portal_ui == 'true' || needs.changes.outputs.seeker_portal_ui == 'true' || needs.changes.outputs.shared_infra == 'true' || needs.changes.outputs.infra == 'true' || needs.changes.outputs.e2e_tests == 'true') }}
    needs:
      - changes
      - deploy-backend
      - deploy-worker
      - deploy-accounts-ui
      - deploy-recruiter-dashboard-ui
      - deploy-recruiter-portal-ui
      - deploy-seeker-portal-ui
      - deploy-shared-infra
      - deploy-infra
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
